---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml
    - vars/ufw.yml

  pre_tasks:
    - name: Ensure apt cache is updated.
      apt: update_cache=true cache_valid_time=600

    - name: Install dependency for pyopenssl.
      apt: name=libssl-dev state=present

  roles:
    - geerlingguy.pip
    - geerlingguy.git
#    - geerlingguy.certbot
    - geerlingguy.nginx
    - geerlingguy.docker
    - weareinteractive.ufw
  
  tasks:
    - import_tasks: tasks/self-signed-cert.yml

    - name: Ensure App docroot exists.
      file:
        path: "{{ app_docroot }}"
        state: directory

    - name: Copy example Node App file in place.
      copy:
        src: files/node-hello/
        dest: "{{ app_docroot }}/node-hello/"
        mode: 0755

    - name: Startup example Docker Container
      shell: >
        docker-compose -f {{ app_docroot }}/node-hello/docker-compose.yml up -d 

    - name: Copy Nginx server configuration in place.
      template:
        src: nginx-conf/nginx.conf.j2
        dest: /etc/nginx/sites-enabled/serverNginx.conf
        mode: 0644
      notify: restart nginx
