version: "3"
services:
  app:
    container_name: hellonode
    restart: always
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
